workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 100
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: HCMUS-19CLC-LETTUTOR
    environment:
      groups:
        - email_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.lettutorApp
      vars:
        APP_ID: 6449217938
      flutter: stable
      xcode: 14.2
      cocoapods: 1.12.1
    scripts:
      - name: Clean Flutter packages
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios
          rm -f Podfile.lock
          rm -rf Pods
          pod cache clean --all
          pod deintegrate
          pod setup
          pod install
          pod repo update
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Flutter build ipa and automatic versioning
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number $APP_ID)
          flutter build ipa --release \
            --build-name=1.0.$(($LATEST_BUILD_NUMBER + 5)) \
            --build-number=$(($LATEST_BUILD_NUMBER + 5)) \
            --export-options-plist=/Users/builder/export_options.plist
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "develop"
          include: true
          source: true
        - pattern: "master"
          include: true
          source: true
      cancel_previous_builds: true
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - $MAIN_EMAIL
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        submit_to_testflight: false
