workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 100
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: HCMUS-19CLC-LETTUTOR
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.lettutorApp
      vars:
        APP_ID: 6449217938
      flutter: stable
      xcode: 14.2
      cocoapods: 1.12.1
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Clean Flutter packages
        script: |
          flutter clean
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios
          rm -f Podfile.lock
          rm -rf Pods
          pod cache clean --all
          pod deintegrate
          pod setup
          pod install
          pod repo update
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Add provisioning profiles
        script: |
          set -e # exit on first failed command

          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
      - name: Add signing certificate
        script: |
          set -e # exit on first failed command

          echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
          keychain initialize
          keychain add-certificates \
              --certificate /tmp/certificate.p12 \
              --certificate-password ${CERTIFICATE_PASSWORD?}
      - name: Increment build number
        script: agvtool new-version -all $BUILD_NUMBER
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa \
          --workspace "${XCODE_WORKSPACE?}" \
          --scheme "${XCODE_SCHEME?}"
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "develop"
          include: true
          source: true
        - pattern: "master"
          include: true
          source: true
        - pattern: "advance-online-app"
          include: true
          source: true
      cancel_previous_builds: true
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - "tgdat19@clc.fitus.edu.vn"
          - "dattruong1220@gmail.com"
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        submit_to_testflight: false
