// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOjkrdxXGBdx2b5wErPVDmm_6c7EECrOc',
    appId: '1:948236125713:web:78f635f1fdade4943213b0',
    messagingSenderId: '948236125713',
    projectId: 'flutter-lettutor',
    authDomain: 'flutter-lettutor.firebaseapp.com',
    storageBucket: 'flutter-lettutor.appspot.com',
    measurementId: 'G-DSR8WD8H2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgskPjIvbBU21PMrj3b5LnfYu02xlqLgI',
    appId: '1:948236125713:android:208e0237d104f5ce3213b0',
    messagingSenderId: '948236125713',
    projectId: 'flutter-lettutor',
    storageBucket: 'flutter-lettutor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnqvDrx7HqITfjNLlUv-NIwQPlraNU9qk',
    appId: '1:948236125713:ios:49dafe9b31e42c863213b0',
    messagingSenderId: '948236125713',
    projectId: 'flutter-lettutor',
    storageBucket: 'flutter-lettutor.appspot.com',
    iosClientId: '948236125713-3t2no926tjvua9hqrp6pbke8m6javv6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.lettutorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnqvDrx7HqITfjNLlUv-NIwQPlraNU9qk',
    appId: '1:948236125713:ios:49dafe9b31e42c863213b0',
    messagingSenderId: '948236125713',
    projectId: 'flutter-lettutor',
    storageBucket: 'flutter-lettutor.appspot.com',
    iosClientId: '948236125713-3t2no926tjvua9hqrp6pbke8m6javv6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.lettutorApp',
  );
}
