// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDngtn84XRA3CLlW_9Lt1TKlNP2EfvXwuw',
    appId: '1:399002733706:web:0ff5b93d1c39e6ad263173',
    messagingSenderId: '399002733706',
    projectId: 'flutter-lettutor-crashlytics',
    authDomain: 'flutter-lettutor-crashlytics.firebaseapp.com',
    storageBucket: 'flutter-lettutor-crashlytics.appspot.com',
    measurementId: 'G-S01SNGPSB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWnxl3BdKH6RovLIlp7mt8xOGA6O8tDc',
    appId: '1:399002733706:android:202d00b6245e639d263173',
    messagingSenderId: '399002733706',
    projectId: 'flutter-lettutor-crashlytics',
    storageBucket: 'flutter-lettutor-crashlytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm4MvmoOzkhL9G6mRHhAqR8iQpEKK8sXk',
    appId: '1:399002733706:ios:45973b3304a4d41f263173',
    messagingSenderId: '399002733706',
    projectId: 'flutter-lettutor-crashlytics',
    storageBucket: 'flutter-lettutor-crashlytics.appspot.com',
    iosClientId: '399002733706-e5mmi0qj6apon68auhegc764jutn70m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lettutorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm4MvmoOzkhL9G6mRHhAqR8iQpEKK8sXk',
    appId: '1:399002733706:ios:45973b3304a4d41f263173',
    messagingSenderId: '399002733706',
    projectId: 'flutter-lettutor-crashlytics',
    storageBucket: 'flutter-lettutor-crashlytics.appspot.com',
    iosClientId: '399002733706-e5mmi0qj6apon68auhegc764jutn70m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.lettutorApp',
  );
}
